import { RouteInfo } from './vertical-sidebar.metadata';

export const RouteAdmin: RouteInfo[] = [
  {
    path: '',
    title: 'Página web',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '',
    title: 'Administración',
    icon: 'fas fa-user',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/users',
        title: 'Usuarios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/roles',
        title: 'Roles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Genéricos',
    icon: 'fas fa-database',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/polls-data/fishing-site',
        title: 'Sitios de desembarco',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-method',
        title: 'Métodos de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-art',
        title: 'Artes de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-area',
        title: 'Áreas de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/species',
        title: 'Especies',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/crops',
        title: 'Cultivos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/boat',
        title: 'Embarcaciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/propulsion-method',
        title: 'Métodos de Propulsión',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Recolección de Datos',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '/pages/reports',
    title: 'Reportes',
    icon: 'fas fa-clipboard-list',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '',
    title: 'Encuestas',
    icon: 'fas fa-chart-bar',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/forms-config/modules',
        title: 'Módulos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/forms',
        title: 'Formularios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/sections',
        title: 'Secciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/questions',
        title: 'Preguntas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Modelos Pesqueros',
    icon: 'fas fa-tachometer-alt',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/models/measurement',
        title: 'Mediciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/weight-check',
        title: 'Control de pesos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/activities',
        title: 'Actividades',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/monitoring',
        title: 'Desembarco',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/industrial-vessel-inspection',
        title: 'Inspección Industrial',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Modelos Agropecuarios',
    icon: 'fas fa-sliders-h',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/models/agricultural-producer',
        title: 'Productor Agropecuario',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/costs-income',
        title: 'Costos e Ingresos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/monitoring-agricultural-prices',
        title: 'Seguimiento de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
];
export const RoutesPesca: RouteInfo[] = [
  {
    path: '',
    title: 'Página web',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '',
    title: 'Administración',
    icon: 'fas fa-user',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/users',
        title: 'Usuarios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/roles',
        title: 'Roles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Genéricos',
    icon: 'fas fa-database',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/polls-data/fishing-site',
        title: 'Sitios de desembarco',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-method',
        title: 'Métodos de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-art',
        title: 'Artes de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-area',
        title: 'Áreas de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/species',
        title: 'Especies',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/crops',
        title: 'Cultivos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/boat',
        title: 'Embarcaciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/propulsion-method',
        title: 'Métodos de Propulsión',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Recolección de Datos',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '/pages/reports',
    title: 'Reportes',
    icon: 'fas fa-clipboard-list',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '',
    title: 'Encuestas',
    icon: 'fas fa-chart-bar',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/forms-config/modules',
        title: 'Módulos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/forms',
        title: 'Formularios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/sections',
        title: 'Secciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/questions',
        title: 'Preguntas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Modelos Pesqueros',
    icon: 'fas fa-tachometer-alt',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/models/measurement',
        title: 'Mediciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/weight-check',
        title: 'Control de pesos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/activities',
        title: 'Actividades',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/monitoring',
        title: 'Desembarco',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/industrial-vessel-inspection',
        title: 'Inspección Industrial',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
];
export const RoutesAgro: RouteInfo[] = [
  {
    path: '',
    title: 'Página web',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '',
    title: 'Administración',
    icon: 'fas fa-user',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/users',
        title: 'Usuarios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/roles',
        title: 'Roles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Genéricos',
    icon: 'fas fa-database',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/polls-data/fishing-site',
        title: 'Sitios de desembarco',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-method',
        title: 'Métodos de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-art',
        title: 'Artes de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/fishing-area',
        title: 'Áreas de Pesca',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/species',
        title: 'Especies',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/crops',
        title: 'Cultivos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/boat',
        title: 'Embarcaciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/polls-data/propulsion-method',
        title: 'Métodos de Propulsión',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Recolección de Datos',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    submenu: [],
  },
  {
    path: '/pages/reports',
    title: 'Reportes',
    icon: 'fas fa-clipboard-list',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '',
    title: 'Encuestas',
    icon: 'fas fa-chart-bar',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/forms-config/modules',
        title: 'Módulos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/forms',
        title: 'Formularios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/sections',
        title: 'Secciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/forms-config/questions',
        title: 'Preguntas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Modelos Agropecuarios',
    icon: 'fas fa-sliders-h',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '/pages/models/agricultural-producer',
        title: 'Productor Agropecuario',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/costs-income',
        title: 'Costos e Ingresos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/pages/models/monitoring-agricultural-prices',
        title: 'Seguimiento de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
];
